"""Render a Markdown summary as a Word document.

Markdown stays the stored form — it greps, diffs and re-renders — and this
produces a .docx from it on demand, so nothing has to be regenerated by the
model to change how the document looks.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

_BOLD = re.compile(r"\*\*(.+?)\*\*")
_BULLET = re.compile(r"^\s*[-*•]\s+")
_HEADING = re.compile(r"^(#{1,6})\s+(.*)$")


def _add_runs(paragraph, text: str) -> None:
    """Write text into a paragraph, honouring **bold** spans.

    Split rather than inserted literally, so the bold is real character
    formatting a reader can restyle, not asterisks in the text.
    """
    position = 0
    for match in _BOLD.finditer(text):
        if match.start() > position:
            paragraph.add_run(text[position:match.start()])
        paragraph.add_run(match.group(1)).bold = True
        position = match.end()
    remainder = text[position:]
    if remainder or not paragraph.runs:
        paragraph.add_run(remainder)


def summary_to_docx(
    markdown: str,
    destination: Path,
    *,
    title: str,
    recorded: str | None = None,
    duration: str | None = None,
    language: str | None = None,
) -> Path:
    """Write `markdown` to `destination` as a .docx and return the path."""
    from docx import Document
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt, RGBColor

    document = Document()

    # A readable body font; the stock Calibri 11 is fine but a touch tight for
    # something people will actually sit and read.
    normal = document.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)
    normal.paragraph_format.space_after = Pt(8)
    normal.paragraph_format.line_spacing = 1.15

    heading = document.add_heading(title, level=0)
    heading.alignment = WD_ALIGN_PARAGRAPH.LEFT

    subtitle_bits = [bit for bit in (recorded, duration, language) if bit]
    if subtitle_bits:
        line = document.add_paragraph()
        run = line.add_run("  ·  ".join(subtitle_bits))
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)
        line.paragraph_format.space_after = Pt(16)

    for raw in (markdown or "").splitlines():
        line = raw.rstrip()
        if not line.strip():
            continue

        match = _HEADING.match(line)
        if match:
            depth = min(len(match.group(1)), 4)
            document.add_heading(match.group(2).strip(), level=max(1, depth))
            continue

        if _BULLET.match(line):
            # A real list style, so Word renumbers and indents it properly
            # rather than treating a literal bullet as ordinary text.
            paragraph = document.add_paragraph(style="List Bullet")
            _add_runs(paragraph, _BULLET.sub("", line).strip())
            continue

        _add_runs(document.add_paragraph(), line.strip())

    footer = document.add_paragraph()
    run = footer.add_run(
        f"Transcribed and summarised locally · {datetime.now().strftime('%d %b %Y')}"
    )
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(0x9C, 0xA3, 0xAF)
    footer.paragraph_format.space_before = Pt(20)

    destination.parent.mkdir(parents=True, exist_ok=True)
    document.save(str(destination))
    return destination
